language: cpp

cache:
  directories:
  - ~/tools/vcpkg

git:
  depth: 1
  quiet: true

# Defaults
os: linux
dist: xenial

compiler: gcc

matrix:
  include:
  - name: GCC
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: g++-7

before_install:
- mkdir ~/tools && cd ~/tools
- wget "https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip" -O ninja-linux.zip
- unzip ninja-linux.zip -d ninja
- export PATH=$PATH:$PWD/ninja/
-|
  if [[ -x ./vcpkg/vcpkg ]]; then
    cd ./vcpkg
    git pull
  else
    git clone --depth=1 --branch=master --quiet https://github.com/Microsoft/vcpkg.git
    eval "CC=gcc-7 && CXX=g++-7"
    ./vcpkg/bootstrap-vcpkg.sh
  fi
- ./vcpkg/vcpkg integrate install

install:
# dependencies
- vcpkg install ms-gsl
- vcpkg install gtest

before_script:
- cd $TRAVIS_BUILD_DIR

script: true

after_script: true

before_cache:
# cleaning up cache
- rm -rf ~/tools/vcpkg/buildtrees
- rm -rf ~/tools/vcpkg/downloads
