language: cpp

git:
  depth: 1
  quiet: true

# Defaults
os: linux
dist: xenial

compiler: gcc

addons:
  apt:
    packages: ninja-build

matrix:
  include:
  - name: GCC
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: g++-7

before_install:
- mkdir -p ~/tools && cd ~/tools
- ninja --version
- |
  # Install vcpkg
  if [[ -x ./vcpkg/vcpkg ]]; then
    cd ./vcpkg
    git pull --quiet
  else
    git clone --depth=1 --branch=master --quiet https://github.com/Microsoft/vcpkg.git
    eval "CC=gcc-7 && CXX=g++-7"
    ./vcpkg/bootstrap-vcpkg.sh
  fi

install:
# dependencies
- cd ~/tools/vcpkg
- ./vcpkg install ms-gsl
- ./vcpkg install gtest

before_script:
- cd $TRAVIS_BUILD_DIR

script: true

before_cache:
- |
  # Cleaning build cache
  rm -rf ~/tools/vcpkg/buildtrees
  rm -rf ~/tools/vcpkg/downloads

cache:
  directories:
  - ~/tools/vcpkg

after_script: true
