language: cpp

git:
  depth: 1
  quiet: true

# Defaults
os: linux
dist: xenial

matrix:
  include:
    - env: COMPILER=g++-7 BUILD_TYPE=Debug


before_install:
- eval "CXX=${COMPILER}"
- mkdir tools || cd ./tools
- git clone --depth=1 --quiet https://github.com/Microsoft/vcpkg.git
- cd vcpkg
- ./bootstrap-vcpkg.sh
- ./vcpkg integrate install

install:
# install dependencies
- ./vcpkg install ms-gsl
- ./vcpkg install gtest


before_script: true

script: true

after_script: true

before_cache: true
# cleaning up cache



