language: cpp

git:
  depth: 1
  quiet: true

# Defaults
os: linux
dist: xenial

# https://apt.llvm.org

matrix:
  include:
  - name: GCC-7
    env:
    - C_compiler=gcc-7
    - CXX_compiler=g++-7
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages:
        - g++-7
        - ninja-build
  - name: Clang-6.0
    dist: Xenial
    env:
    - C_compiler=clang-6.0
    - CXX_compiler=clang++-6.0
    addons:
      apt:
        sources:
        - llvm-toolchain-xenial-6.0
        packages:
        - clang-6.0
        - ninja-build
  - name: Clang-7
    dist: Xenial
    env:
    - C_compiler=clang-7
    - CXX_compiler=clang++-7
    addons:
      apt:
        sources:
        - llvm-toolchain-xenial-7
        packages:
        - clang-7
        - lld-7
        - libc++-7-def
        - libc++abi-7-def
        - ninja-build

before_install:
- mkdir -p ~/tools && cd ~/tools
- ninja --version
- |
  # Install vcpkg
  if [[ -x ./vcpkg/vcpkg ]]; then
    cd ./vcpkg
    git pull --quiet
  else
    git clone --depth=1 --branch=master --quiet https://github.com/Microsoft/vcpkg.git
    eval "CC=${C_compiler} && CXX=${CXX_compiler}"
    ./vcpkg/bootstrap-vcpkg.sh
  fi

install:
# dependencies
- cd ~/tools/vcpkg
- ./vcpkg install ms-gsl
- ./vcpkg install gtest

before_script:
- cd $TRAVIS_BUILD_DIR

script: true

before_cache:
- |
  # Cleaning build cache
  rm -rf ~/tools/vcpkg/buildtrees
  rm -rf ~/tools/vcpkg/downloads

cache:
  directories:
  - ~/tools/vcpkg

after_script: true
