language: cpp

git:
  depth: 1
  quiet: true

# Defaults
os: linux
dist: xenial

env:
  global:
  - NINJA_VER=v1.8.2
  - NINJA_URL="https://github.com/ninja-build/ninja/releases/download/${NINJA_VER}/ninja-linux.zip"
  - NINJA_SHA512='38fcb68e745c1f15b4b50f20069ffe686b1ef5baf93b74958e132ea5d30d155cf6970d6dc1b095aafd421ebd8bcc63acf4f64e305c496266b5182f99b815cca5  ./ninja-linux.zip'

# https://apt.llvm.org
# https://github.com/travis-ci/apt-source-safelist/blob/master/ubuntu.json
# https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

matrix:
  include:
  - name: GCC-7
    env:
    - C_compiler=gcc-7
    - CXX_compiler=g++-7

  - name: Clang-6.0
    dist: xenial
    env:
    - C_compiler=clang-6.0
    - CXX_compiler=clang++-6.0
    addons:
      apt:
        sources:
        - llvm-toolchain-xenial-6.0
        packages:
        - clang-6.0

  - name: Clang-7
    dist: xenial
    env:
    - C_compiler=clang
    - CXX_compiler=clang++

before_install:
- mkdir -p ~/tools && cd ~/tools
- wget -q "${NINJA_URL}" --tries=3 -nc -O ninja-linux.zip
- |
  { # Install Ninja-build
    sum=$(sha512sum ./ninja-linux.zip)
    if [[ $sum = ${NINJA_SHA512} ]]; then
      unzip -q ninja-linux.zip -d ninja
      export PATH=$PATH:$PWD/ninja/
    else
      echo "Ninja hash has changed!"  >&2
      echo "Expecting: $NINJA_SHA512" >&2
      echo "Actual:    $sum"          >&2
      exit 1
    fi
  }
- |
  # Install vcpkg
  if [[ -x ./vcpkg/vcpkg ]]; then
    cd ./vcpkg
    git pull --quiet
  else
    git clone --depth=1 --branch=master --quiet https://github.com/Microsoft/vcpkg.git
    eval "CC=gcc-7 && CXX=g++-7"
    ./vcpkg/bootstrap-vcpkg.sh
  fi

install:
- |
  # dependencies
  cd ~/tools/vcpkg
  eval "CC=${C_compiler} && CXX=${CXX_compiler}"
- ./vcpkg install ms-gsl
- ./vcpkg install gtest

before_script:
- cd $TRAVIS_BUILD_DIR

script: true

before_cache:
- |
  # Cleaning build cache
  rm -rf ~/tools/vcpkg/buildtrees
  rm -rf ~/tools/vcpkg/downloads

cache:
  directories:
  - ~/tools/vcpkg

after_script: true
