##====---- .travis.yml                                                ----====##
# https://apt.llvm.org
# https://github.com/travis-ci/apt-source-safelist/blob/master/ubuntu.json
# https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test
##====--------------------------------------------------------------------====##
language: cpp

git:
  quiet: true

env:
  global:
  - NINJA_VER: v1.8.2
  - NINJA_SHA512: "38fcb68e745c1f15b4b50f20069ffe686b1ef5baf93b74958e132ea5d30d155cf6970d6dc1b095aafd421ebd8bcc63acf4f64e305c496266b5182f99b815cca5  ninja-linux.zip"
  - TOOLCHAIN_FILE: "$HOME/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"

##====--------------------------------------------------------------------====##
## Define Build Configurations
# Defaults
os: linux
dist: xenial

matrix:
  include:
  - name: GCC-7
    env:
    - C_compiler:   gcc-7
    - CXX_compiler: g++-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7

  - name: GCC-8
    env:
    - C_compiler:   gcc-8
    - CXX_compiler: g++-8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8

  - name: Clang-6.0
    dist: xenial
    env:
    - C_compiler: clang-6.0
    - CXX_compiler: clang++-6.0
    addons:
      apt:
        sources:
        - llvm-toolchain-xenial-6.0
        - ubuntu-toolchain-r-test
        packages:
        - clang-6.0
        - g++-7
        - lld-6.0

  - name: Clang-6.0 libc++
    dist: xenial
    env:
    - C_compiler: clang-6.0
    - CXX_compiler: clang++-6.0
    - CXX_lib=libc++
    addons:
      apt:
        sources:
        - llvm-toolchain-xenial-6.0
        - llvm-toolchain-xenial-7
        - ubuntu-toolchain-r-test
        packages:
        - clang-6.0
        - g++-7
        - libc++-7-dev
        - libc++abi-7-dev
        - lld-6.0

  - name: Clang-7
    dist: xenial
    env:
    - C_compiler:   clang
    - CXX_compiler: clang++
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7

  - name: Clang-7 libc++
    dist: xenial
    env:
    - C_compiler:   clang
    - CXX_compiler: clang++
    - CXX_lib: libc++
    addons:
      apt:
        sources:
        - llvm-toolchain-xenial-7
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libc++-7-dev
        - libc++abi-7-dev

  allow_failures:
  - name: Clang-6.0 libc++
  - name: Clang-7 libc++

##====--------------------------------------------------------------------====##
## Install tools and dependencies
before_install:
- |
  # Setup
  set -e # stop Bash execution on error
  mkdir -p ~/tools
  eval "CC=${C_compiler:-$CC} && CXX=${CXX_compiler:-$CXX}"
- |
  # Install Ninja-build
  (
    os=${TRAVIS_OS_NAME}
    file_name="ninja-${os}.zip"
    NINJA_URL="https://github.com/ninja-build/ninja/releases/download/${NINJA_VER}/${file_name}"
    cd ~/tools
    wget -q "${NINJA_URL}" --tries=3 -nc
    sum=$(sha512sum ${file_name})
    if [[ $sum = ${NINJA_SHA512} ]]; then
      unzip -q ${file_name} -d ninja
    else
      echo "Ninja hash has changed!"  >&2
      echo "Expecting: $NINJA_SHA512" >&2
      echo "Actual:    $sum"          >&2
      exit 1
    fi
  )
  export PATH=$PATH:$HOME/tools/ninja/
- |
  # Install vcpkg
  (
    cd ~/tools
    if [[ -x ./vcpkg/vcpkg ]]; then
      cd ./vcpkg
      git pull --quiet
    else
      git clone --depth=1 --branch=master --quiet https://github.com/Microsoft/vcpkg.git
      if [[ ${TRAVIS_OS_NAME} == linux && ${CXX_compiler} != g++* || ${CXX_compiler%g++-} < 7 ]]
      then
        eval "CC=gcc-7 && CXX=g++-7"
      fi
      ./vcpkg/bootstrap-vcpkg.sh
    fi
  )
- |
  # Using libc++
  if [[ ${CXX_compiler} == clang* && ${CXX_lib} ]]; then
    FLAGS="-stdlib=${CXX_lib}"
    #if [[ ${CXX_lib} == libc++ ]]; then
    #  FLAGS="${FLAGS} -lc++fs"
    #  FLAGS="${FLAGS} -lc++experimental"
    #fi
    export CXXFLAGS=$FLAGS
  fi

install:
- cd ~/tools/vcpkg
- ./vcpkg install ms-gsl
- ./vcpkg install gtest

##====--------------------------------------------------------------------====##
before_script:
- cd $TRAVIS_BUILD_DIR

script:
- echo $CXX
- $CXX --version
- cmake --version
- ninja --version
- ~/tools/vcpkg/vcpkg list
- if [[ ! -e ${TOOLCHAIN_FILE:?} ]]; then exit 1; fi

##====--------------------------------------------------------------------====##
before_cache:
- |
  # Cleaning build cache
  rm -rf ~/tools/vcpkg/buildtrees
  rm -rf ~/tools/vcpkg/downloads

cache:
  directories:
  - ~/tools/vcpkg

##====--------------------------------------------------------------------====##
after_script: true
