language: cpp

git:
  depth: 1
  quiet: true

# Defaults
os: linux
dist: xenial

compiler: gcc

matrix:
  include:
  - name: GCC
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages: g++-7

before_install:
- ls && mkdir tools && cd ./tools
- git clone --depth=1 --quiet https://github.com/Microsoft/vcpkg.git
- cd vcpkg
- eval "CC=gcc-7 && CXX=g++-7"
- ./bootstrap-vcpkg.sh
- ./vcpkg integrate install

install:
# dependencies
- ./vcpkg install ms-gsl
- ./vcpkg install gtest


before_script: true

script: true

after_script: true

before_cache: true
# cleaning up cache



